export const restaurants = {
    "results_found": 4406,
    "results_start": 0,
    "results_shown": 10,
    "restaurants": [
      {
        "restaurant": {
          "R": {
            "res_id": 16587684
          },
          "apikey": "censored",
          "id": "16587684",
          "name": "Andre's Cucina & Polenta Bar",
          "url": "https://www.zomato.com/adelaide/andres-cucina-polenta-bar-city-centre?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "location": {
            "address": "94 Frome Street, Adelaide",
            "locality": "Frome Street, City Centre",
            "city": "Adelaide",
            "city_id": 297,
            "latitude": "-34.9244652001",
            "longitude": "138.6078929901",
            "zipcode": "5000",
            "country_id": 14,
            "locality_verbose": "Frome Street, City Centre, Adelaide, SA"
          },
          "switch_to_order_menu": 0,
          "cuisines": "Italian",
          "average_cost_for_two": 100,
          "price_range": 4,
          "currency": "$",
          "offers": [],
          "opentable_support": 0,
          "is_zomato_book_res": 0,
          "mezzo_provider": "DIMMI",
          "is_book_form_web_view": 0,
          "book_form_web_view_url": "",
          "thumb": "https://b.zmtcdn.com/data/res_imagery/16587684_RESTAURANT_9dc512abb12e7d9018e5199610270bb7_c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
          "user_rating": {
            "aggregate_rating": "4.9",
            "rating_text": "Excellent",
            "rating_color": "3F7E00",
            "votes": "831"
          },
          "photos_url": "https://www.zomato.com/adelaide/andres-cucina-polenta-bar-city-centre/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
          "menu_url": "https://www.zomato.com/adelaide/andres-cucina-polenta-bar-city-centre/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
          "featured_image": "https://b.zmtcdn.com/data/res_imagery/16587684_RESTAURANT_9dc512abb12e7d9018e5199610270bb7_c.jpg",
          "medio_provider": "",
          "has_online_delivery": 0,
          "is_delivering_now": 0,
          "include_bogo_offers": true,
          "deeplink": "zomato://restaurant/16587684",
          "is_table_reservation_supported": 1,
          "has_table_booking": 1,
          "book_url": "https://www.zomato.com/adelaide/andres-cucina-polenta-bar-city-centre/book?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "events_url": "https://www.zomato.com/adelaide/andres-cucina-polenta-bar-city-centre/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "establishment_types": []
        }
      },
      {
        "restaurant": {
          "R": {
            "res_id": 16587626
          },
          "apikey": "censored",
          "id": "16587626",
          "name": "Mandoo Korean Dumplings",
          "url": "https://www.zomato.com/adelaide/mandoo-korean-dumplings-city-centre?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "location": {
            "address": "3/26 Bank Street, Adelaide",
            "locality": "Bank Street, City Centre",
            "city": "Adelaide",
            "city_id": 297,
            "latitude": "-34.9225175430",
            "longitude": "138.5974917188",
            "zipcode": "5000",
            "country_id": 14,
            "locality_verbose": "Bank Street, City Centre, Adelaide, SA"
          },
          "switch_to_order_menu": 0,
          "cuisines": "Korean, Dumplings",
          "average_cost_for_two": 45,
          "price_range": 2,
          "currency": "$",
          "offers": [],
          "opentable_support": 0,
          "is_zomato_book_res": 0,
          "mezzo_provider": "OTHER",
          "is_book_form_web_view": 0,
          "book_form_web_view_url": "",
          "book_again_url": "",
          "thumb": "https://b.zmtcdn.com/data/res_imagery/16587626_RESTAURANT_59e967927b3a71e90cf152f50b9a9945_c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
          "user_rating": {
            "aggregate_rating": "4.9",
            "rating_text": "Excellent",
            "rating_color": "3F7E00",
            "votes": "717"
          },
          "photos_url": "https://www.zomato.com/adelaide/mandoo-korean-dumplings-city-centre/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
          "menu_url": "https://www.zomato.com/adelaide/mandoo-korean-dumplings-city-centre/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
          "featured_image": "https://b.zmtcdn.com/data/res_imagery/16587626_RESTAURANT_59e967927b3a71e90cf152f50b9a9945_c.jpg?output-format=webp",
          "has_online_delivery": 0,
          "is_delivering_now": 0,
          "include_bogo_offers": true,
          "deeplink": "zomato://restaurant/16587626",
          "is_table_reservation_supported": 0,
          "has_table_booking": 0,
          "events_url": "https://www.zomato.com/adelaide/mandoo-korean-dumplings-city-centre/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "establishment_types": []
        }
      },
      {
        "restaurant": {
          "R": {
            "res_id": 17841283
          },
          "apikey": "censored",
          "id": "17841283",
          "name": "Luigi Delicatessen",
          "url": "https://www.zomato.com/adelaide/luigi-delicatessen-city-centre?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "location": {
            "address": "151 Flinders Street, Adelaide, City Centre, Adelaide",
            "locality": "Flinders Street, City Centre",
            "city": "Adelaide",
            "city_id": 297,
            "latitude": "-34.9269276762",
            "longitude": "138.6064747721",
            "zipcode": "5000",
            "country_id": 14,
            "locality_verbose": "Flinders Street, City Centre, Adelaide, SA"
          },
          "switch_to_order_menu": 0,
          "cuisines": "Coffee and Tea, Italian, Cafe Food",
          "average_cost_for_two": 45,
          "price_range": 2,
          "currency": "$",
          "offers": [],
          "opentable_support": 0,
          "is_zomato_book_res": 0,
          "mezzo_provider": "OTHER",
          "is_book_form_web_view": 0,
          "book_form_web_view_url": "",
          "book_again_url": "",
          "thumb": "https://b.zmtcdn.com/data/res_imagery/17841283_RESTAURANT_111708211f92d4057a66ce140d23f905.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
          "user_rating": {
            "aggregate_rating": "4.9",
            "rating_text": "Excellent",
            "rating_color": "3F7E00",
            "votes": "100"
          },
          "photos_url": "https://www.zomato.com/adelaide/luigi-delicatessen-city-centre/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
          "menu_url": "https://www.zomato.com/adelaide/luigi-delicatessen-city-centre/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
          "featured_image": "https://b.zmtcdn.com/data/res_imagery/17841283_RESTAURANT_111708211f92d4057a66ce140d23f905.jpg",
          "has_online_delivery": 0,
          "is_delivering_now": 0,
          "include_bogo_offers": true,
          "deeplink": "zomato://restaurant/17841283",
          "is_table_reservation_supported": 0,
          "has_table_booking": 0,
          "events_url": "https://www.zomato.com/adelaide/luigi-delicatessen-city-centre/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "establishment_types": []
        }
      },
      {
        "restaurant": {
          "R": {
            "res_id": 16588873
          },
          "apikey": "censored",
          "id": "16588873",
          "name": "Peel St",
          "url": "https://www.zomato.com/adelaide/peel-st-city-centre?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "location": {
            "address": "9 Peel Street, City Centre, Adelaide",
            "locality": "Peel Street, City Centre",
            "city": "Adelaide",
            "city_id": 297,
            "latitude": "-34.9233805556",
            "longitude": "138.5979472222",
            "zipcode": "5000",
            "country_id": 14,
            "locality_verbose": "Peel Street, City Centre, Adelaide, SA"
          },
          "switch_to_order_menu": 0,
          "cuisines": "Asian, Middle Eastern, Modern Australian",
          "average_cost_for_two": 110,
          "price_range": 4,
          "currency": "$",
          "offers": [],
          "opentable_support": 0,
          "is_zomato_book_res": 0,
          "mezzo_provider": "OTHER",
          "is_book_form_web_view": 0,
          "book_form_web_view_url": "",
          "book_again_url": "",
          "thumb": "https://b.zmtcdn.com/data/res_imagery/16588873_RESTAURANT_5da4f9d595c057645e26c74aee4e5007.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
          "user_rating": {
            "aggregate_rating": "4.8",
            "rating_text": "Excellent",
            "rating_color": "3F7E00",
            "votes": "371"
          },
          "photos_url": "https://www.zomato.com/adelaide/peel-st-city-centre/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
          "menu_url": "https://www.zomato.com/adelaide/peel-st-city-centre/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
          "featured_image": "https://b.zmtcdn.com/data/res_imagery/16588873_RESTAURANT_5da4f9d595c057645e26c74aee4e5007.jpg",
          "has_online_delivery": 0,
          "is_delivering_now": 0,
          "include_bogo_offers": true,
          "deeplink": "zomato://restaurant/16588873",
          "is_table_reservation_supported": 0,
          "has_table_booking": 0,
          "events_url": "https://www.zomato.com/adelaide/peel-st-city-centre/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "establishment_types": []
        }
      },
      {
        "restaurant": {
          "R": {
            "res_id": 16587245
          },
          "apikey": "censored",
          "id": "16587245",
          "name": "Wasai Japanese Kitchen",
          "url": "https://www.zomato.com/adelaide/wasai-japanese-kitchen-city-centre?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "location": {
            "address": "15 Field Street, Adelaide",
            "locality": "Field Street, City Centre",
            "city": "Adelaide",
            "city_id": 297,
            "latitude": "-34.9308757855",
            "longitude": "138.5961227864",
            "zipcode": "5000",
            "country_id": 14,
            "locality_verbose": "Field Street, City Centre, Adelaide, SA"
          },
          "switch_to_order_menu": 0,
          "cuisines": "Japanese",
          "average_cost_for_two": 70,
          "price_range": 3,
          "currency": "$",
          "offers": [],
          "opentable_support": 0,
          "is_zomato_book_res": 0,
          "mezzo_provider": "OTHER",
          "is_book_form_web_view": 0,
          "book_form_web_view_url": "",
          "book_again_url": "",
          "thumb": "https://b.zmtcdn.com/data/res_imagery/16587245_RESTAURANT_ddee046dd352ca5be7947df5a1dae692_c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
          "user_rating": {
            "aggregate_rating": "4.8",
            "rating_text": "Excellent",
            "rating_color": "3F7E00",
            "votes": "909"
          },
          "photos_url": "https://www.zomato.com/adelaide/wasai-japanese-kitchen-city-centre/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
          "menu_url": "https://www.zomato.com/adelaide/wasai-japanese-kitchen-city-centre/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
          "featured_image": "https://b.zmtcdn.com/data/res_imagery/16587245_RESTAURANT_ddee046dd352ca5be7947df5a1dae692_c.jpg?output-format=webp",
          "has_online_delivery": 0,
          "is_delivering_now": 0,
          "include_bogo_offers": true,
          "deeplink": "zomato://restaurant/16587245",
          "is_table_reservation_supported": 0,
          "has_table_booking": 0,
          "events_url": "https://www.zomato.com/adelaide/wasai-japanese-kitchen-city-centre/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "establishment_types": []
        }
      },
      {
        "restaurant": {
          "R": {
            "res_id": 16586858
          },
          "apikey": "censored",
          "id": "16586858",
          "name": "Chianti",
          "url": "https://www.zomato.com/adelaide/chianti-city-centre?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "location": {
            "address": "160 Hutt Street, Adelaide",
            "locality": "Hutt Street, City Centre",
            "city": "Adelaide",
            "city_id": 297,
            "latitude": "-34.9307777778",
            "longitude": "138.6123972222",
            "zipcode": "5000",
            "country_id": 14,
            "locality_verbose": "Hutt Street, City Centre, Adelaide, SA"
          },
          "switch_to_order_menu": 0,
          "cuisines": "Italian",
          "average_cost_for_two": 80,
          "price_range": 3,
          "currency": "$",
          "offers": [],
          "opentable_support": 0,
          "is_zomato_book_res": 0,
          "mezzo_provider": "DIMMI",
          "is_book_form_web_view": 0,
          "book_form_web_view_url": "",
          "thumb": "https://b.zmtcdn.com/data/res_imagery/16586858_RESTAURANT_4c7f2fd1757d62c10d61c9c97070488e.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
          "user_rating": {
            "aggregate_rating": "4.7",
            "rating_text": "Excellent",
            "rating_color": "3F7E00",
            "votes": "810"
          },
          "photos_url": "https://www.zomato.com/adelaide/chianti-city-centre/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
          "menu_url": "https://www.zomato.com/adelaide/chianti-city-centre/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
          "featured_image": "https://b.zmtcdn.com/data/res_imagery/16586858_RESTAURANT_4c7f2fd1757d62c10d61c9c97070488e.jpg",
          "medio_provider": "",
          "has_online_delivery": 0,
          "is_delivering_now": 0,
          "include_bogo_offers": true,
          "deeplink": "zomato://restaurant/16586858",
          "is_table_reservation_supported": 1,
          "has_table_booking": 1,
          "book_url": "https://www.zomato.com/adelaide/chianti-city-centre/book?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "events_url": "https://www.zomato.com/adelaide/chianti-city-centre/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "establishment_types": []
        }
      },
      {
        "restaurant": {
          "R": {
            "res_id": 16589382
          },
          "apikey": "censored",
          "id": "16589382",
          "name": "Bread & Bone Wood Grill",
          "url": "https://www.zomato.com/adelaide/bread-bone-wood-grill-city-centre?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "location": {
            "address": "15 Peel Street, Adelaide",
            "locality": "Peel Street, City Centre",
            "city": "Adelaide",
            "city_id": 297,
            "latitude": "-34.9235027778",
            "longitude": "138.5981305556",
            "zipcode": "5000",
            "country_id": 14,
            "locality_verbose": "Peel Street, City Centre, Adelaide, SA"
          },
          "switch_to_order_menu": 0,
          "cuisines": "American, Bar Food",
          "average_cost_for_two": 75,
          "price_range": 3,
          "currency": "$",
          "offers": [],
          "opentable_support": 0,
          "is_zomato_book_res": 0,
          "mezzo_provider": "OTHER",
          "is_book_form_web_view": 0,
          "book_form_web_view_url": "",
          "book_again_url": "",
          "thumb": "https://b.zmtcdn.com/data/res_imagery/16589382_RESTAURANT_8d7735e5f3a11707abed6348b6e1b2ca_c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
          "user_rating": {
            "aggregate_rating": "4.7",
            "rating_text": "Excellent",
            "rating_color": "3F7E00",
            "votes": "587"
          },
          "photos_url": "https://www.zomato.com/adelaide/bread-bone-wood-grill-city-centre/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
          "menu_url": "https://www.zomato.com/adelaide/bread-bone-wood-grill-city-centre/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
          "featured_image": "https://b.zmtcdn.com/data/res_imagery/16589382_RESTAURANT_8d7735e5f3a11707abed6348b6e1b2ca_c.jpg",
          "has_online_delivery": 0,
          "is_delivering_now": 0,
          "include_bogo_offers": true,
          "deeplink": "zomato://restaurant/16589382",
          "is_table_reservation_supported": 0,
          "has_table_booking": 0,
          "events_url": "https://www.zomato.com/adelaide/bread-bone-wood-grill-city-centre/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "establishment_types": []
        }
      },
      {
        "restaurant": {
          "R": {
            "res_id": 16587066
          },
          "apikey": "censored",
          "id": "16587066",
          "name": "Muratti Cakes",
          "url": "https://www.zomato.com/adelaide/muratti-cakes-prospect?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "location": {
            "address": "114-114b Prospect Road, Prospect, Prospect, Adelaide",
            "locality": "Prospect Road, Prospect",
            "city": "Adelaide",
            "city_id": 297,
            "latitude": "-34.8871638889",
            "longitude": "138.5939944444",
            "zipcode": "5082",
            "country_id": 14,
            "locality_verbose": "Prospect Road, Prospect, Adelaide, SA"
          },
          "switch_to_order_menu": 0,
          "cuisines": "Bakery, Patisserie",
          "average_cost_for_two": 35,
          "price_range": 2,
          "currency": "$",
          "offers": [],
          "opentable_support": 0,
          "is_zomato_book_res": 0,
          "mezzo_provider": "OTHER",
          "is_book_form_web_view": 0,
          "book_form_web_view_url": "",
          "book_again_url": "",
          "thumb": "https://b.zmtcdn.com/data/res_imagery/16587066_RESTAURANT_383cdc1857c641a8a7b6afb5d6fd30da_c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
          "user_rating": {
            "aggregate_rating": "4.7",
            "rating_text": "Excellent",
            "rating_color": "3F7E00",
            "votes": "288"
          },
          "photos_url": "https://www.zomato.com/adelaide/muratti-cakes-prospect/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
          "menu_url": "https://www.zomato.com/adelaide/muratti-cakes-prospect/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
          "featured_image": "https://b.zmtcdn.com/data/res_imagery/16587066_RESTAURANT_383cdc1857c641a8a7b6afb5d6fd30da_c.jpg",
          "has_online_delivery": 0,
          "is_delivering_now": 0,
          "include_bogo_offers": true,
          "deeplink": "zomato://restaurant/16587066",
          "is_table_reservation_supported": 0,
          "has_table_booking": 0,
          "events_url": "https://www.zomato.com/adelaide/muratti-cakes-prospect/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "establishment_types": []
        }
      },
      {
        "restaurant": {
          "R": {
            "res_id": 16608070
          },
          "apikey": "censored",
          "id": "16608070",
          "name": "d'Arry's Verandah Restaurant",
          "url": "https://www.zomato.com/adelaide/darrys-verandah-restaurant-mclaren-vale?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "location": {
            "address": "Osborn Rd, McLaren Vale",
            "locality": "McLaren Vale",
            "city": "Adelaide",
            "city_id": 297,
            "latitude": "-35.1983720000",
            "longitude": "138.5452420000",
            "zipcode": "5171",
            "country_id": 14,
            "locality_verbose": "McLaren Vale"
          },
          "switch_to_order_menu": 0,
          "cuisines": "Modern Australian, Australian",
          "average_cost_for_two": 25000017,
          "price_range": 1,
          "currency": "$",
          "offers": [],
          "opentable_support": 0,
          "is_zomato_book_res": 0,
          "mezzo_provider": "DIMMI",
          "is_book_form_web_view": 0,
          "book_form_web_view_url": "",
          "thumb": "https://b.zmtcdn.com/data/reviews_photos/68d/a53c499c4e881aa4a903df20b3d8068d_1521678455.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
          "user_rating": {
            "aggregate_rating": "4.7",
            "rating_text": "Excellent",
            "rating_color": "3F7E00",
            "votes": "201"
          },
          "photos_url": "https://www.zomato.com/adelaide/darrys-verandah-restaurant-mclaren-vale/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
          "menu_url": "https://www.zomato.com/adelaide/darrys-verandah-restaurant-mclaren-vale/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
          "featured_image": "https://b.zmtcdn.com/data/reviews_photos/68d/a53c499c4e881aa4a903df20b3d8068d_1521678455.jpg",
          "medio_provider": "",
          "has_online_delivery": 0,
          "is_delivering_now": 0,
          "include_bogo_offers": true,
          "deeplink": "zomato://restaurant/16608070",
          "is_table_reservation_supported": 1,
          "has_table_booking": 1,
          "book_url": "https://www.zomato.com/adelaide/darrys-verandah-restaurant-mclaren-vale/book?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "events_url": "https://www.zomato.com/adelaide/darrys-verandah-restaurant-mclaren-vale/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "establishment_types": []
        }
      },
      {
        "restaurant": {
          "R": {
            "res_id": 16588993
          },
          "apikey": "censored",
          "id": "16588993",
          "name": "Orana",
          "url": "https://www.zomato.com/adelaide/orana-city-centre?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "location": {
            "address": "285 Rundle Street, Adelaide",
            "locality": "Rundle Street, City Centre",
            "city": "Adelaide",
            "city_id": 297,
            "latitude": "-34.9226260000",
            "longitude": "138.6101280000",
            "zipcode": "05000",
            "country_id": 14,
            "locality_verbose": "Rundle Street, City Centre, Adelaide, SA"
          },
          "switch_to_order_menu": 0,
          "cuisines": "Australian",
          "average_cost_for_two": 350,
          "price_range": 4,
          "currency": "$",
          "offers": [],
          "opentable_support": 0,
          "is_zomato_book_res": 0,
          "mezzo_provider": "DIMMI",
          "is_book_form_web_view": 0,
          "book_form_web_view_url": "",
          "thumb": "https://b.zmtcdn.com/data/res_imagery/16588993_RESTAURANT_f6bfd6ddbff70706b0c8707a9b316dfd_c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
          "user_rating": {
            "aggregate_rating": "4.7",
            "rating_text": "Excellent",
            "rating_color": "3F7E00",
            "votes": "146"
          },
          "photos_url": "https://www.zomato.com/adelaide/orana-city-centre/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
          "menu_url": "https://www.zomato.com/adelaide/orana-city-centre/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
          "featured_image": "https://b.zmtcdn.com/data/res_imagery/16588993_RESTAURANT_f6bfd6ddbff70706b0c8707a9b316dfd_c.jpg",
          "medio_provider": "",
          "has_online_delivery": 0,
          "is_delivering_now": 0,
          "include_bogo_offers": true,
          "deeplink": "zomato://restaurant/16588993",
          "is_table_reservation_supported": 1,
          "has_table_booking": 1,
          "book_url": "https://www.zomato.com/adelaide/orana-city-centre/book?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "events_url": "https://www.zomato.com/adelaide/orana-city-centre/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "establishment_types": []
        }
      }
    ]
  };